default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: touch-stamp-files
        name: Touch package commit stamp files before commit
        entry: python3 scripts/touch_stamp_files.py
        language: system
        stages: [pre-commit]
        always_run: true
        pass_filenames: true
      - id: show-ci-progress
        name: Show CI progress
        entry: scripts/wait_ci.py $(scripts/get_gh_run_id_for_last_commit.sh)
        language: system
        stages: [pre-push]
        always_run: true
        pass_filenames: false